// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables
if (!SUPABASE_URL) {
  console.error('VITE_SUPABASE_URL is not set. Please configure it in your environment.');
}
if (!SUPABASE_PUBLISHABLE_KEY) {
  console.error('VITE_SUPABASE_ANON_KEY is not set. Please configure it in your environment.');
}

// Debug: print runtime supabase url (temporary)
try {
  // show only hostname to avoid leaking keys in shared logs
  const url = SUPABASE_URL ? new URL(SUPABASE_URL).hostname : 'undefined';
  console.warn('[debug] Supabase host:', url, ' — window.location:', typeof window !== 'undefined' ? window.location.href : 'server');
} catch (e) {
  console.warn('[debug] Supabase URL parse error', e);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});